### ISSUE TITLE
If there is an `\e` modifier inside a `<bg=#bada55>` it closes the background color

### ISSUE THREAD

**Issue by xiCO2k** [nunomaduro/termwind#101]
## Code:

```php
render(<<<'HTML'
    <div class="my-1 ml-3 px-2 bg-green-300 text-black">
        🍃 Termwind now have the capability to <b>extend</b> colors!
    </div>
HTML);
```

## Result:

![image](https://user-images.githubusercontent.com/823088/141779737-e06d339d-3e7c-4b28-9c3b-2f6f3ab4974e.png)

## Posible Solution:

* Change `<bg>` to and `\e` code
* Or, find if there is any way to only remove the escape code added from `<b>`.

**Comment by xiCO2k** [comment]
Another issue related to this one is this:

### Code:
```php
<div class="my-1 ml-3 px-2 bg-green-300 text-black">
    🍃 Termwind <b><i>now <s>have</s> the</i> capability</b> to extend colors!
</div>
```

### It renders:
![image](https://user-images.githubusercontent.com/823088/142483918-12b41d21-32a5-4869-915e-b99f825b59f3.png)

```bash
\e[30;48;2;186;218;85m  🍃 Termwind \e[1m\e[3mnow \e[9mhave\e[0m the\e[0m capability\e[0m to extend colors!  \e[39;49m\n
```

### Solution:
So what happens, is the \e[0m cancels all the escape codes added before and to have it working properly it need to be re-added.

**Comment by xiCO2k** [comment]
@butschster I think this could be a related thing to the #64. Any ideas about this?

Thanks

**Comment by butschster** [comment]
> @butschster I think this could be a related thing to the #64. Any ideas about this?
> 
> Thanks

Hy, yes! #64 will solve the problem. I'll try to finish this PR on this weekend!

**Comment by xiCO2k** [comment]
That would be awesome, really thanks for your help.

**Comment by butschster** [comment]
@xiCO2k Hm, I've just discovered the problem and I think my PR can't fix it) 

I think the best way is to replace `\e` with options and fix tests and then style inheritance will fix colors.

```
<bg=#86efac;fg=black>  🍃 Termwind now have the capability to <bg=#86efac;fg=black;options=bold>extend</> colors!  </>
```

**Comment by xiCO2k** [comment]
Yes, the probably is some of the `\e` we don't have the `options`, so we may need another way.

Style Inheritance is the first step 😄

**Comment by Bittu69** [comment]
I agree, Style Inheritance is the first step

**Comment by butschster** [comment]
> I agree, Style Inheritance is the first step

You can try style inheritance right now with my last PR #102

**Comment by xiCO2k** [comment]
After giving this a try, I found no issue anymore.
