### ISSUE TITLE
Color is not applied on windows terminal with wsl.

### ISSUE THREAD

**Issue by opuu** [nunomaduro/termwind#109]
Default colors are not being applied to html element on windows terminal (using windows sub system for linux).
Also the parser trying to parse special characters as html, in this case <== gives an warning.

```php
require __DIR__ . '/vendor/autoload.php';

use function Termwind\{render};

// single line html...
render('<div class="p-1 bg-green-300">Termwind</div><span class="text-red-200"><== this was supposed to be green.<span>');
```
## Output
![image](https://user-images.githubusercontent.com/77793409/145439345-7d1ee367-61c7-423d-a1e9-a0f81d9bc95c.png)

**Comment by nunomaduro** [comment]
@opuu Can you try to pull request a fix for those two issues?

**Comment by opuu** [comment]
@nunomaduro I'll try. Have you tested this on windows? I am getting the same result on CMD, PowerShell and Windows Terminal. But on Linux and Visual Studio Code integrated terminal it seems to work as expected.

### CMD
![cmd](https://user-images.githubusercontent.com/77793409/145455927-ddbc9842-1b7d-4569-8085-e339b72d5b66.PNG)

### PowerShell
![powershell](https://user-images.githubusercontent.com/77793409/145455994-268e2ba3-88ea-4222-800a-73e6327e100e.PNG)

### PowerShell (Windows Terminal)
![ps-terminal](https://user-images.githubusercontent.com/77793409/145456095-84c13cdb-74a9-4725-b0c6-d26bbd9bfef1.PNG)

###  Visual Studio Code
![vscode](https://user-images.githubusercontent.com/77793409/145456220-79c7c9d8-380b-4047-9f4c-7e5b250b3a6b.png)

**Comment by xiCO2k** [comment]
@opuu thanks for the report, we did not spent anytime checking it on Windows, but we need too. Thanks for bringing that to the table.

**Comment by xiCO2k** [comment]
@opuu We will probably need to have the LIBXML_NOERROR added to have support for the HTML5 tags like `<header>` so that could be a solution for this issue

**Comment by opuu** [comment]
@xiCO2k Yes adding LIBXML_NOERROR to loadHTML will fix the issue.

It will also stop showing errors for invalid html. But this should not be a problem as the ending tag is automatically generated from the starting tag, and 
termwind is replacing unsupported tags with div. 

```php
<?php

$dom = new DOMDocument();

$dom->loadHTML('<header data-attribute="foo">bar<', LIBXML_NOERROR | LIBXML_COMPACT | LIBXML_HTML_NODEFDTD | LIBXML_NOBLANKS | LIBXML_NOXMLDECL);

echo $dom->saveHTML();

?>
```

And here is the [official documentation from Microsoft about text formatting on console.](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN#text-formatting)

**Comment by xiCO2k** [comment]
Yes if you to contribute with that change I will be happy to review!

**Comment by opuu** [comment]
@xiCO2k After spending hours debugging the code, I found nothing wrong that can cause the color issue, reading[ symphony console documentation](https://symfony.com/doc/current/console/coloring.html) I found that windows command console does not support ANSI by default. You have to enable it, and the process is very dirty.

>By default, the Windows command console doesn't support output coloring. The Console component disables output coloring for Windows systems, but if your commands invoke other scripts which emit color sequences, they will be wrongly displayed as raw escape characters. Install the Cmder, ConEmu, ANSICON, Mintty (used by default in GitBash and Cygwin) or Hyper free applications to add coloring support to your Windows command console.

I am creating  a PR for the HTML5 compatibility issue.

**Comment by xiCO2k** [comment]
Thanks @opuu. Really appreciate your time. Looking forward to the PR.
