### ISSUE TITLE
unexpected '|' in Functions.php on line 17

### ISSUE THREAD

**Issue by ahosker** [nunomaduro/termwind#114]
I'm using [spatie/laravel-health](https://github.com/spatie/laravel-health) which requires **nunomaduro/termwind 1.1** but receveing the following error.

I can not figure out why. It's not happening in dev environment but when I try and deploy to staging environment on Laravel Forge.

`PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/user/site/vendor/nunomaduro/termwind/src/Functions.php on line 17`

There is a pipe on line 17 but not sure on usage, I presume its used correctly?

https://github.com/nunomaduro/termwind/blob/2a047696be3343fda0e4df8f47e1531a0a0bfae5/src/Functions.php#L17

**Comment by ahosker** [comment]
My mistake, I wasn't running PHP 8

**Comment by bureaug** [comment]
Hi,

well I am using PHP 8.2 and still getting exactly the same error for Laravel cron jobs. This is quite critical so if you can take a look, please.

Thanks

**Comment by xiCO2k** [comment]
It should not be a problem, can you make sure you are really using `php8`?

**Comment by bureaug** [comment]
The cronjob was using a different PHP and yes, after fixing that string, all went smoothly again. My bad.

**Comment by xiCO2k** [comment]
No worries. Thanks

**Comment by Jeremiahiro** [comment]
I just met this error despite trying various PHP versions

**Comment by rphan312** [comment]
Currently still having this issue. Laravel 10 with PHP 8.27. It's the only error in my error logs
