### ISSUE TITLE
Testing an Artisan command using render()

### ISSUE THREAD

**Issue by eleftrik** [nunomaduro/termwind#121]
Is it possible to test an Artisan command's console output (via `expectsOutput`, `doesntExpectOutput`) which is using, for example, `render()` function?

Artisan command `foo`:
```php
...
render('bar'); // even with no styling/HTML
...

```

Unit PEST:
```php
it('does not show output foo string', function () {
    $this->artisan('foo')
        ->doesntExpectOutput('bar');
});

```

Apparently, there is no difference between using `render('bar')` or not: the test always passes.
Am I doing anything wrong?

Thank you

**Comment by xiCO2k** [comment]
Hey @eleftrik, thanks for the issue, we want to support expectations, but is not yet available, if you want to contribute, feel free to do it.

I will keep this issue open.

Thanks.
