### ISSUE TITLE
Injecting variable when rendering a template

### ISSUE THREAD

**Issue by dib258** [nunomaduro/termwind#124]
Hi,

I was recently trying to use Termwind with Laravel Zero to make a small cli/php app.

After trying to print the first layout with Termwind, I can't get my head around the possibility to inject a variable in the template before rendering it.

Either I miss something, either I'm in a specific case (Laravel Zero, which has striped a lot of functionality of Laravel).

1. First attempt is with a nowdoc  and trying different way to print write a variable but with no luck 

```php
use function Termwind\render;

$test = 'hello';
render(<<<'HTML'
        <div>
            <div class="px-1 bg-green-600">test : </div>
            <div class="ml-1">
                {$test}<br>
                $test<br>
                ${test}<br>
                {{ $test }}<br>
                <?php $test; <br>
            </div>
        </div>
HTML);
```
With this as an output :
```bash
 test : 
 {$test}
$test
${test}
{{ $test }}

```

2. Second attempt :  I tried to use the view helper with a blade file. Since in Laravel Zero there's no resources folder with blade files, I created thoses folder `resources/views` and the file `termwind.blade.php` with the template with the previous template.
I found out that the view helper is present but there was no `ViewServiceProvider`.

```php
    'providers' => [
        App\Providers\AppServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
    ],
```
This was a good try but Laravel Zero just have a subset of `laravel/framework`. Just the `Foundation` folder not the `View` one.
I could try to pull the whole `laravel/framework` but I think it's not the way to go.
Here was the code I wanted to try : 

```php
use function Termwind\render;

$test = 'hello';
render(view('termwind', compact('test')));
```

3. The last attempt : I've seen another way to build the HTML template with chained methods :

```php
use function Termwind\div;
use function Termwind\render;

$test = 'hello';
div([
    div('test', 'px-1 bg-green-600'),
    div($test, 'ml-1'),
])->render();
```

I get the following error :

```bash
 Error

  Call to undefined function Termwind\div()
```

I am actually now out of idea to try this. Any help appreciated!
I'm using : 
- php 8.1.2
- nunomaduro/termwind : v1.4.3
- laravel-zero/framework : v8.9.1
- laravel-zero/foundation : v8.81.0

Thanks for reading me and I'm hoping this can help others that want to use this wonderful tool you created !

**Comment by jdreesen** [comment]
Did you try it like this?

```php
use function Termwind\render;

$test = 'hello';
render(<<<HTML   # <-- note the missing single quotes!
        <div>
            <div class="px-1 bg-green-600">test : </div>
            <div class="ml-1">
                {$test}<br>
                $test<br>
                ${test}<br>
                {{ $test }}<br>
                <?php $test; <br>
            </div>
        </div>
HTML);
```

**Comment by dib258** [comment]
Oh my god thank you, what a sneaky nowdoc !

```bash
 test
 hello
hello
hello
{{ hello }}
```

Thank you for that fast answer, I should have searched more on that nowdoc notation.
