### ISSUE TITLE
when <p> label with background style disorder

### ISSUE THREAD

**Issue by kayw-geek** [nunomaduro/termwind#132]
I found that `my` will take effect on the blank line, and this blank line will be applied with the background color, resulting in style confusion.

```html 
render(<<<'HTML'
    <div class="mx-2 my-1 space-y-1">

        <div class="bg-red"><p>xcccccccccccccccccccccccccccccccccccccccccccccccc</p></div>

    </div>
HTML);
```
![image](https://user-images.githubusercontent.com/29700073/161703545-9e4654a4-5ccf-4846-8945-5c89b44a59de.png)
If this is a BUG, I am willing to fix it, but I may need some guidance.

**Comment by xiCO2k** [comment]
Hey @kayw-geek there is some issues related with the `bg-` colors with line breaks, my suggestion for now is to add the `bg` class on every line, until we figure a good way to handle the line breaks with background colors.
