### ISSUE TITLE
Styles are not applied on iterm

### ISSUE THREAD

**Issue by Sergiobop** [nunomaduro/termwind#145]
Hello everyone

I didn't know whether to create this issue in this repository or in the Laravel repository. I have created the issue here since in the latest version of Laravel this package is used under the hood for the refreshed UI.

New Laravel commands don't render properly when using iterm, for example, the new `php artisan about` command:

Iterm:
<img width="1045" alt="Captura de Pantalla 2022-07-20 a las 10 40 37" src="https://user-images.githubusercontent.com/73531831/179938223-a70cfe86-52b0-4af8-a2a2-e87e25131654.png">

Terminal:
<img width="472" alt="Captura de Pantalla 2022-07-20 a las 10 41 28" src="https://user-images.githubusercontent.com/73531831/179938187-fa4333bb-0a32-45c4-b1a0-45df00467b60.png">

Is there something I have to configure beforehand or am I missing something?

Thanks a lot

**Comment by xiCO2k** [comment]
Hey @Sergiobop, it looks like it something related with your theme, can you try another and let me know if it works?

Thanks.

**Comment by Sergiobop** [comment]
I fresh installed the PowerLevel10k (had PowerLevel9k) following these steps https://gist.github.com/kevin-smets/8568070 (ZSH_THEME="powerlevel10k/powerlevel10k")


The issue is still here. Screenshot:
<img width="571" alt="Captura de Pantalla 2022-07-20 a las 11 07 40" src="https://user-images.githubusercontent.com/73531831/179943842-8582abe1-fe07-417a-a588-c3e0b7331ed6.png">

I tried the "agnoster" theme too, same results

Thanks @xiCO2k

**Comment by xiCO2k** [comment]
Check this comment: https://gist.github.com/kevin-smets/8568070?permalink_comment_id=4040810#gistcomment-4040810

Probably related.

**Comment by Sergiobop** [comment]
Ok some achievements here:

Unchecking "Brighten bold text" in iTerm profile color settings fixed the color problems:
<img width="558" alt="Captura de Pantalla 2022-07-20 a las 11 17 04" src="https://user-images.githubusercontent.com/73531831/179945845-4560ebac-69e4-4f8f-9187-3a878e6d68ae.png">

Adjusting the "Minimum contrast" from 0 to 15:
<img width="575" alt="Captura de Pantalla 2022-07-20 a las 11 18 26" src="https://user-images.githubusercontent.com/73531831/179946164-30bfd652-bc91-4835-afe2-b00e885e4dbe.png">

Thanks a lot @xiCO2k

**Comment by xiCO2k** [comment]
Awesome! glad you solved it.
