### ISSUE TITLE
Line-wrapped / nested elements don't behave as expected

### ISSUE THREAD

**Issue by AdamGaskins** [nunomaduro/termwind#150]
Would like to use in a few more advanced scenarios, but there's a few cases where line-wrapping and nesting elements cause different behaviors from what I'd expect in HTML:

## Line automatically wrapping example
```html
<div class="m-1 p-1 bg-gray w-35">
    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
</div>
```

![image](https://user-images.githubusercontent.com/1180782/183534917-cb3aa23f-bb9d-4ec6-bb84-372d662b19e6.png)

## Nested elements with padding example
```html
<div class="w-64 bg-gray p-1">
    <span class="w-1/2 bg-red mr-1 p-1">
        Left
    </span>

    <span class="w-1/2 bg-red p-1">
        Right
    </span>
</div>
```

![image](https://user-images.githubusercontent.com/1180782/183535939-9ca98d3b-5e21-4944-88e6-fc20bd1be907.png)

Thanks again for this project!

**Comment by xiCO2k** [comment]
Hey @AdamGaskins 

We are aware of that case on the multi line text wrap, right now we act as `whitespace-nowrap` by default, would love to review a PR with the other whitespace classes available 😎.

For that drop on the Left and Right Example I think is the margin on the first element, for that you can use `flex` on the parent div and then use `flex-1` on each elem.

Thanks.
