### ISSUE TITLE
Flex with padding

### ISSUE THREAD

**Issue by jkniest** [nunomaduro/termwind#157]
Heyho,

when using flex to render columns besided each other and then applying padding to each of the boxes causes a weird result.

Working, without padding
```php
        render(<<<HTML
            <div class="flex mt-1 justify-evenly">
                <span class="flex-1 bg-green-100">
                    Today:
                </span>
                <span class="flex-1 bg-green-200">
                    Tomorrow:
                </span>
            </div>
        HTML);
```

![CleanShot 2022-11-20 at 02 41 23](https://user-images.githubusercontent.com/15618191/202878758-9955c229-2e47-40fe-81b8-325466de7045.png)

---

But when applying padding to the boxes they are not properly aligned anymore:

```php
        render(<<<HTML
            <div class="flex mt-1 justify-evenly">
                <span class="flex-1 bg-green-100 p-1">
                    Today:
                </span>
                <span class="flex-1 bg-green-200 p-1">
                    Tomorrow:
                </span>
            </div>
        HTML);
```

![CleanShot 2022-11-20 at 02 41 34](https://user-images.githubusercontent.com/15618191/202878767-a4c88026-014a-43e2-9bfb-9e4daca9c4b6.png)

Did I something wrong? I will try to look into the library to figure it out, but maybe I'm just using it wrong 😅 Thanks for the awesome library!

**Comment by xiCO2k** [comment]
Hey @jkniest I think if you go with just `px-1` it should work, multi line flex is not yet supported :(
