### ISSUE TITLE
Is there a way to have a default answer for the ask() methods?

### ISSUE THREAD

**Issue by eliottchampault** [nunomaduro/termwind#160]
Hello there,

Thank you so much for this amazing package. I am sorry to create and issue as this is more of a question. 

Would it be possible to have a default answer for the ask() method? Something "a la" ```Symfony\Component\Console\Question\ConfirmationQuestion;``` where the second param (I believe optional) is the default aswer in case the user press the 'return' key.

Let me know.

All the best

Eliott

**Comment by xiCO2k** [comment]
Hey Elliot, we will probably remove `ask` from Termwind core api, and it will have its own plugin in the future with all of that support.

Thanks.

**Comment by eliottchampault** [comment]
Is there a roadmap for Termwind?
