### ISSUE TITLE
There's no output at all when an artisan call that uses termwind is called within a command that also uses termwind

### ISSUE THREAD

**Issue by emiliopedrollo** [nunomaduro/termwind#161]
A simple example of this issue can be found here: spatie/laravel-health#150.

> It happens because Termwind has an static variable $renderer for it's output and when an Artisan call is made with a command that also uses Termwind this static variable is updated to use BufferedOutput instead of the default ConsoleOutput.

**Comment by xiCO2k** [comment]
No issue here, maybe a fix is needed on `laravel-health`.
