### ISSUE TITLE
Supported Colors Listing

### ISSUE THREAD

**Issue by nickpoulos** [nunomaduro/termwind#166]
Really awesome project, thanks for creating it. I had a quick question related to colors. 

According to the docs we should be able to use any of the colors within Tailwind CSS, but it seems like not all variations or colors are supported?  I do not remember running into this issue during other previous projects which used Termwind.  I am wondering if there is another issue at play here. 

Are the specific supported colors related to the terminal software you are using? Bash vs. ZSH? or maybe other terminal settings/plugins/themes?  Or is there a more refined list of colors which Termwind supports that is not as extensive as everything available via Tailwind.

**Comment by xiCO2k** [comment]
Hey @nickpoulos we are not supporting all the variants yet, but if you want to contribute with that I would love to check your PR.

We support the bash colors, and you can use the defaults from `text-red`, `text-blue`, etc...
