### ISSUE TITLE
Required the support of branching and looping

### ISSUE THREAD

**Issue by avinash-usualsmart** [nunomaduro/termwind#169]
Can you please provide support for loops and conditional statements like native PHP?

![image](https://user-images.githubusercontent.com/103576878/221652743-afe82401-01fa-42ff-b86d-d152fd464070.png)

This is my code and I want a list of all directories to be printed with for loop.

![image](https://user-images.githubusercontent.com/103576878/221652336-a316dbcd-31f9-484a-93c3-99a3b2935340.png)

Let me know how can I help.

Thanks.

**Comment by xiCO2k** [comment]
Try to use blade views for the loops.

**Comment by avinash-usualsmart** [comment]
How to use view without having laravel?

**Comment by avinash-usualsmart** [comment]
> Try to use blade views for the loops.

Hello @xiCO2k, what if I am not using Laravel?
