### ISSUE TITLE
Fatal Error when running schedule:work

### ISSUE THREAD

**Issue by JonPurvis** [nunomaduro/termwind#170]
Hello 👋 

I'm using this package as part of Laravel Zero. Within my application, If I run `schedule:work`, it'll start successfully but then sometimes after ~10 seconds, fail with:

> Symfony\Component\ErrorHandler\Error\FatalError: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes)

Looking at the error in our Sentry instance, the error seems to be in [/vendor/nunomaduro/termwind/src/ValueObjects/Styles.php](https://github.com/nunomaduro/termwind/blob/master/src/ValueObjects/Styles.php) and is:

```php
public function with(array $properties): self
{
    $this->properties = array_replace_recursive($this->properties, $properties);
    return $this;
}
```

As an additional note, we've not actually done anything with Termwind in the application. The only Termwind usage I can see is in the default `InspireCommand` class, but that has the schedule commented out so it's not even included when running `schedule:work`. 

I'd appreciate someone looking into this, if you need any more information, let me know!

Thanks

**Comment by xiCO2k** [comment]
Hey @JonPurvis can you setup a dummy project with this error?

I did try and everything went fine.

Thanks.

**Comment by JonPurvis** [comment]
Hey @xiCO2k,

Thanks for replying! I actually tried removing the Termwind usage from `InspireCommand` to see if that stops the error and it seems to have done so! Still rather strange seeing as though that command is never ran...

I'll close this issue for now but will reopen if it crops back up.

Thanks again
