### ISSUE TITLE
Overwrite previous render

### ISSUE THREAD

**Issue by WyriHaximus** [nunomaduro/termwind#172]
I'm working on this table with progress for specific items. This all works fine and well, but when using terminal clear and repainting it there is a lot of flickering in the terminal. Is there a suggested way to overwrite a previous render?

 ![image](https://user-images.githubusercontent.com/147145/233208357-ffdbd14c-153b-467f-bf74-e4c29556dac0.png)

**Comment by xiCO2k** [comment]
you can take a look on this plugin: https://github.com/xiCO2k/termwind-plugin-live
