### ISSUE TITLE
a href doesn't work in Windows 10 console and under wsl

### ISSUE THREAD

**Issue by 2rkmen** [nunomaduro/termwind#173]
a href doesn't work in Windows 10 console and under wsl.
Is it working on a mac or Linux?
Is there some solution to avoid this problem?

**Comment by xiCO2k** [comment]
can you share a printscreen? and the HTML provided?

**Comment by 2rkmen** [comment]
i use it in laravel zero

```php 
    public function handle()
    {
        render(<<<'HTML'
            <p>
                This is a CLI app built with Termwind. <a href="/">Click here to open</a>
            </p>
        HTML);
    }
```

![image](https://github.com/nunomaduro/termwind/assets/8482586/cd997c49-3a6b-4d7f-bf53-4e7ce753b6b6)

**Comment by xiCO2k** [comment]
It maybe a problem with `symfony/console`, can you try this, and let me know if it works?

```php
use Symfony\Component\Console\Output\ConsoleOutput;

(new ConsoleOutput())->write('<href=http://google.pt>Test</>');
```

**Comment by 2rkmen** [comment]
no. same situation. Links are not clickable on windows command line and wsl

I think this feature not available under windows. 
https://stackoverflow.com/questions/62375976/windows-terminal-clickable-urls

Is it work on linux?

**Comment by withinboredom** [comment]
Whether links are clickable depends on the terminal application you are using. In Windows, if you are using [Terminal](https://www.microsoft.com/store/productid/9N0DX20HK701?ocid=pdpshare), you have to ctrl-click to open a link in the browser. On Linux, it is the same with Tilex or most terminal applications.

If you are using the old style terminal in windows, it doesn't support opening links via clicks IIRC. I don't even know how to get to it anymore, so I can't easily test it.

**Comment by 2rkmen** [comment]
thank you. It works on new terminal
