### ISSUE TITLE
[Bug] Console output does not affect `--no-ansi` option

### ISSUE THREAD

**Issue by sebb-m0** [nunomaduro/termwind#175]
Hi,

coming from a different project, which uses termwind to style command output: https://github.com/TomasVotruba/lines/issues/35#issuecomment-1711297745

It's a symfony command, which uses build in options for coloring console output (or leave it as it is).

Using termwind as styling leads to ignoring the `--no-ansi` option.

![Screenshot 2023-09-08 at 09 43 00](https://github.com/nunomaduro/termwind/assets/126587502/dcc343d9-4175-43c8-a8f6-b54eaed0efeb)

The screenshot shows the output, which shows ansi colors. That the colors are coliding with my iTerm2 agnoster theme leads me to that problem, that `--no-ansi` is not working.

**Comment by xiCO2k** [comment]
Hey @sebb-m0 I tried to replicate this issue with no success.

Will close this one, but keep me posted.
