### ISSUE TITLE
Styling issues with \e[0m

### ISSUE THREAD

**Issue by devacse** [nunomaduro/termwind#66]
Check this example

![image](https://user-images.githubusercontent.com/12087263/137954663-32a2ad3d-8f5e-48fd-9180-a9b04e0ec871.png)

I am trying to use green-text color for the entire div. But after font-bold it resets all the styles.

![image](https://user-images.githubusercontent.com/12087263/137955003-e666fa8d-ceee-479e-a224-0ed3d8fabcc3.png)

Its because of \e[0m. Why are we resetting all the stylings?

Check this gist => https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797

To reset each style it has its own number (i.e bold=> \e[22m, italic =>  \e[23m ...)

Is there any specific reason for going with \e[0m?

This is after I used the style specific ending sequences instead of \e[0m.

![image](https://user-images.githubusercontent.com/12087263/137955679-5e512850-c05f-464f-a3bb-0ed727280bf7.png)

**Comment by xiCO2k** [comment]
Hey @devacse there is already a pull request to handle the style inheritance check #64. That should solve this one. Thanks.
