### ISSUE TITLE
Add styles support for a `<pre>` tag.

### ISSUE THREAD

**Issue by xiCO2k** [nunomaduro/termwind#91]
Right now it's not possible to add styles to the `<pre>` tag element.

**Comment by xiCO2k** [comment]
@butschster Do you think that is possible?

**Comment by butschster** [comment]
I thought about it. I think yes, we can split HTML inside pre element into lines, add styles to each line and then implode into HTML and render

**Comment by butschster** [comment]
@xiCO2k I created PR #96 where you can look at the result of applying styles to a content inside pre element.
