### ISSUE TITLE
[bug] Empty spaces between two elements

### ISSUE THREAD

**Issue by butschster** [nunomaduro/termwind#94]
Hi guys!

Let's imagine two situations

**Fist**
Two elements, each on a new line
```html
<div>
    <span class="px-1">hello</span>
    <span class="px-1">world</span>
</div>
```

**Second**
Two element on one line with space
```html
<div>
    <span class="px-1">hello</span> <span class="px-1">world</span>
</div>
```

And what behavior we should expect on each case. I suggest the following behavior

In the first case we can remove empty space
```html
&nbsp;hello&nbsp;&nbsp;world&nbsp;
```

In the second case we can keep space
```html
&nbsp;hello&nbsp;&nbsp;&nbsp;world&nbsp;
```

**Comment by butschster** [comment]
@xiCO2k @nunomaduro what do you think?

**Comment by xiCO2k** [comment]
Thanks @butschster. I like it.
